name: Sentrey Release

on:
  release:
    types: [published]

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: memorial-sloan-kettering
          SENTRY_PROJECT: oncokb
        with:
          tagName: ${{ github.ref }}
          environment: production
          releaseNamePrefix: oncokb-
