name: Sentry Release

on:
  release:
    types: [ published ]

jobs:
  createSentryRelease:
    if: github.repository == 'oncokb/oncokb'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create a Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: memorial-sloan-kettering
          SENTRY_PROJECT: oncokb
        with:
          version: ${{ github.ref_name }}
          environment: production
